### ISSUE TITLE
ChromeDriver connection issue

### ISSUE THREAD

**Issue by vincent-artea** [nanasess/setup-chromedriver#140]
Since yesterday I'm having this issue in our CI using `setup-chromedriver` with Selenium tests:

> 2023-03-17T06:17:40.2267884Z org.openqa.selenium.remote.http.ConnectionFailedException: 
> 2023-03-17T06:17:40.2268593Z Unable to establish websocket connection to http://localhost:44213/devtools/browser/76d507ce-e5b8-4d92-b766-98f9303c6e73
> 2023-03-17T06:17:40.2269075Z Build info: version: '4.8.1', revision: '8ebccac989'
> 2023-03-17T06:17:40.2269561Z System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1034-azure', java.version: '17.0.6'
> 2023-03-17T06:17:40.2273938Z Driver info: driver.version: ChromeDriver`

We haven't changed anything to our tests or the Github action configuration, and everything works fine in local. Any idea how to fix this annoying issue, blocking our CI ?

**Comment by nanasess** [comment]
@vincent-artea Is the following helpful?
https://stackoverflow.com/a/75736688

**Comment by vincent-artea** [comment]
Yes! Thanks a lot!
