### ISSUE TITLE
Need to specify full version

### ISSUE THREAD

**Issue by ianneub** [nanasess/setup-chromedriver#155]
In order for me to use this action I needed to specify the full version number, like so:

```yaml
- uses: nanasess/setup-chromedriver@v2.0.0
```

The README indicated that setting the version to `v2` should work.

**Comment by nanasess** [comment]
@ianneub 
Sorry, created v2 branch.
Now you can use v2 as per the README.
```yaml
- uses: nanasess/setup-chromedriver@v2
```
