### ISSUE TITLE
Github Actions failed after adding support for install to google-chrome

### ISSUE THREAD

**Issue by michaelangelocobo** [nanasess/setup-chromedriver#19]
Github Actions suddenly failed due to setup-chromedriver. Maybe this error is related to the recently added codes?
....
    - uses: nanasess/setup-chromedriver@master
....
....

Download action repository 'nanasess/setup-chromedriver@master'
Error: Could not find file '/home/runner/work/_actions/_temp_*******/_staging/nanasess-setup-chromedriver-eb06ff5/node_modules/jest-jasmine2/node_modules/.bin/jest-runtime'.

**Comment by nanasess** [comment]
@michaelangelocobo Please try to re-run it😥

**Comment by pierredup** [comment]
Failures are still there, I'm currently getting the following error:

```
Download action repository 'nanasess/setup-chromedriver@master'
Error: Could not find file '/home/runner/work/_actions/_temp_f4c7ab2c-0f7d-44b5-8cc3-86a37119639c/_staging/nanasess-setup-chromedriver-62e6b45/node_modules/jest-haste-map/node_modules/.bin/sane'.
```

**Comment by pierredup** [comment]
Using a specific commit before the updates in `node_modules` works fine

```yaml
- uses: nanasess/setup-chromedriver@1bf03f69846dfda39180ff7b250765e6e96256b7
```

**Comment by nanasess** [comment]
@pierredup Thanks for the detailed issue.
Please try the following:

```yaml
- uses: nanasess/setup-chromedriver@1e17a06902b9926f1baa08758ba90769022fc205
```

**Comment by pierredup** [comment]
Thank you for the quick feedback @nanasess. That commit works perfectly 👍🏼

**Comment by nanasess** [comment]
@pierredup @michaelangelocobo 
Thanks you so much!, Fixed version has been released.
https://github.com/nanasess/setup-chromedriver/releases/tag/v1.0.3
