### ISSUE TITLE
Error 404 when downloading

### ISSUE THREAD

**Issue by tagliala** [nanasess/setup-chromedriver#190]
```
##setup chromedriver
/home/runner/work/_actions/nanasess/setup-chromedriver/v2/lib/setup-chromedriver.sh  linux64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   1[9](https://github.com/diowa/ruby3-rails7-bootstrap-heroku/actions/runs/5664695183/job/15348359218?pr=575#step:4:10)3    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Error: The process '/home/runner/work/_actions/nanasess/setup-chromedriver/v2/lib/setup-chromedriver.sh' failed with exit code 22
```

Ref: https://github.com/diowa/ruby3-rails7-bootstrap-heroku/actions/runs/5665831080/job/15351356245?pr=575

--- 

I think that it is because chromedriver 115 has not been uploaded yet

**Comment by nanasess** [comment]
We will expedite support for Chrome for Testing.
https://github.com/nanasess/setup-chromedriver/issues/175

**Comment by bseeger** [comment]
Thank you for working on this so quickly! We are also experiencing this issue.

**Comment by stell** [comment]
TDD is on pause :) Fingers crossed.

**Comment by worldroot** [comment]
🤞🤞

**Comment by worldroot** [comment]
hey @bseeger , @stell , @tagliala you can fix the version in the action + in your rails_helper for now until theres is an update here :  ( so that your pipeline are not stuck )
in your github action :
```
  - uses: nanasess/setup-chromedriver@v2.0.0 
      with:
        chromedriver-version: '114.0.5735.90'`
```

in your rails_helper : 
`Webdrivers::Chromedriver.required_version = '114.0.5735.90'`

**Comment by dan-mba** [comment]
Chromedriver has moved the endpoint to get the filenames for 115+.
It is now a JSON file here https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json

**Comment by nanasess** [comment]
Thank you all for your contributions!, Fixed version has been released.
https://github.com/nanasess/setup-chromedriver/releases/tag/v2.1.0

**Comment by ejskipper** [comment]
Hi there! Thanks for the speedy update here.

I found that after updating to use @v2, I still got an issue:
```
 Webdrivers::VersionError:
            Unable to find latest point release version for 115.0.5790. You appear to be using a non-production version of Chrome. Please set `Webdrivers::Chromedriver.required_version = <desired driver version>` to a known chromedriver version: https://chromedriver.storage.googleapis.com/index.html
```
            
I can see that some other users had a similar issue [here](https://github.com/CircleCI-Public/browser-tools-orb/issues/75#issuecomment-1640923560), and a follow-up patch was released.
 
Do we need something similar here? Not sure if the issue can be fixed from within the setup-chromedriver action

For now I have implemented a workaround by manually installing an older version of Chrome, which works fine, but would be great to remove that. 
 
 My workaround, in case anyone else has the same issue:
```
      - name: Install Chrome
        run: |
          # Add the Google Chrome repository
          wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb \
          && sudo apt install -y --allow-downgrades /tmp/chrome.deb \
          && rm /tmp/chrome.deb
      
      - name: Set up chrome driver
        uses: nanasess/setup-chromedriver@v2

```

**Comment by mcalthrop** [comment]
> My workaround, in case anyone else has the same issue:
> 
> ```
>       - name: Install Chrome
>         run: |
>           # Add the Google Chrome repository
>           wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb \
>           && sudo apt install -y --allow-downgrades /tmp/chrome.deb \
>           && rm /tmp/chrome.deb
>       
>       - name: Set up chrome driver
>         uses: nanasess/setup-chromedriver@v2
> ```

@ejskipper I haven't been able to get the solution above to work.

Here's the URL for version `114.0.5735.90`, for example, and it returns a 404:
https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.90_amd64.deb

**Comment by tagliala** [comment]
The issue reported by me has been fixed in the laste version of `setup-chromedriver` action (2.1) and there is no need to make changes to the workflow

**Comment by ejskipper** [comment]
All working fine for me now, thanks! 

I'm no longer using the above workaround, but just in case anyone needs it for some reason, I was using CHROME_VERSION: "114.0.5735.198-1". (cc @mcalthrop )
