### ISSUE TITLE
Downloading `chromedriver` fails

### ISSUE THREAD

**Issue by petschki** [nanasess/setup-chromedriver#199]
Recently we get the following error from curl:

```
Run nanasess/setup-chromedriver@v2
  with:
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.17/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.8.17/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.17/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.17/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.17/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.17/x64/lib
##setup chromedriver
/home/runner/work/_actions/nanasess/setup-chromedriver/v2/lib/setup-chromedriver.sh  linux64
Installing ChromeDriver 115.0.5790.110 for linux64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  232k  100  232k    0     0  2425k      0 --:--:-- --:--:-- --:--:-- 2425k
Downloading 
curl: Remote file name has no length!
curl: (23) Failed writing received data to disk/application
Error: The process '/home/runner/work/_actions/nanasess/setup-chromedriver/v2/lib/setup-chromedriver.sh' failed with exit code 23
```

Were there changes on the download rate limit at Google?

**Comment by johantell** [comment]
It started working for me just now (had the issue described above). Same for you?

**Comment by nanasess** [comment]
@petschki Are the problems still persisting?

**Comment by robbl** [comment]
I have the same issue. Before I was using @v1 and notices some 404 errors, when the action tried to download chromedriver. Now I switched to @v2 see the same error as above. I've got a setup with a build matrix and some jobs randomly fail and others finish successfully.

**Comment by petschki** [comment]
Its indeed a bit flaky but it occurred right now again.

**Comment by nanasess** [comment]
@robbl @petschki 
Please provide a link to the GitHub Actions for success and failure.

**Comment by nanasess** [comment]
@robbl @petschki 
Looking at the status of Chrome for Testing, it appears that version 115.0.5790.110, which failed to download ChromeDriver, is failing to build.
![image](https://github.com/nanasess/setup-chromedriver/assets/815715/0980e656-8917-42e3-a946-ffc8dfd75340)

https://googlechromelabs.github.io/chrome-for-testing/

**Comment by petschki** [comment]
Aha! so pinning the version should fix this for now:
```
  with:
    chromerdriver-version: '115.0.5790.102'
```

**Comment by petschki** [comment]
Would it be possible to use
```
  with:
    chromerdriver-version: 'stable'
```
?

**Comment by nanasess** [comment]
@petschki 
Probably because your GitHub Actions are using Chrome 115.0.5790.110.
In this case, it is best to use:
```
with:
    chromerdriver-version: '115.0.5790.102'
```

**Comment by nanasess** [comment]
Rewriting in TypeScript would allow for flexible error handling.
https://github.com/nanasess/setup-chromedriver/issues/159

Since this is a Chrome for Testing issue, this issue is closed.

@petschki @robbl @johantell 
Thank you so much for all the information you provided!🙏
