### ISSUE TITLE
Failures downloading 115

### ISSUE THREAD

**Issue by dnys1** [nanasess/setup-chromedriver#200]
Currently seeing lots of failures when trying to download ChromeDriver 115 on Linux runners

```
Run nanasess/setup-chromedriver@6fb8f5ffa6b7dc11e631ff695fbd2fec0b04bb52
##setup chromedriver
/home/runner/work/_actions/nanasess/setup-chromedriver/6fb8f5ffa6b7dc11e631ff695fbd2fec0b04bb52/lib/setup-chromedriver.sh  linux64
Installing ChromeDriver 115.0.5790.110 for linux64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  236k  100  236k    0     0  1478k      0 --:--:-- --:--:-- --:--:-- 1481k
Downloading 
curl: Remote file name has no length!
curl: (23) Failed writing received data to disk/application
Error: The process '/home/runner/work/_actions/nanasess/setup-chromedriver/6fb8f5ffa6b7dc11e631ff695fbd2fec0b04bb52/lib/setup-chromedriver.sh' failed with exit code 23
```

**Comment by nanasess** [comment]
@dnys1 `115.0.5790.110`  seems to have failed to build.
Please check the following:
https://github.com/nanasess/setup-chromedriver/issues/199#issuecomment-1662063574

**Comment by aeros281** [comment]
Wouldn't locking chrome-driver cause mismatch between `chrome` & `chromedriver` because the action install the latest `chrome`?

**Comment by ahukkanen** [comment]
We are currently experiencing the same issue.

Just throwing this as an idea here as I may not know all the consequences of my suggestion, but how about fetching the latest point release of the same Chrome version in case the `URL` is empty at this point (as in this particular error):
https://github.com/nanasess/setup-chromedriver/blob/79a04bdb07abf5d76f3809290c34719f68e6143f/lib/setup-chromedriver.sh#L65

I mean before that line, checking the `$URL` variable if it is empty and then fetching the latest point release as a fallback mechanism like:

```
curl  --location --fail --retry 10 https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json | jq -r ".versions[] | select(.version | startswith(\"$(echo $VERSION | cut -d '.' -f1-3).\")) | .version" | tail -1
```

E.g. for the problematic version `115.0.5790.110`, this would fetch all the releases starting with `115.0.5790.`. This would return the following list of versions:

```
115.0.5790.3
115.0.5790.13
115.0.5790.24
115.0.5790.56
115.0.5790.75
115.0.5790.90
115.0.5790.98
115.0.5790.102
115.0.5790.170
```

And picking the last one with the `tail -1` pipe would result to setting the version number to `115.0.5790.170`.

Do you see some issue with this approach as a fallback mechanism? I understand that the legacy `http://chromedriver.storage.googleapis.com/LATEST_RELEASE_114` URL is doing something similar and that could also result into version conflicts between Chromedriver and Chrome. I would imagine that by discarding only the last part of the version number would not result to any major incompatibilities.

**Comment by nanasess** [comment]
@ahukkanen 
Thank you for your suggestion.🙏
In addition to setup-chromedriver.sh, there is also setup-chromedriver.ps1 support.
We don't want to complicate the shell script or PowerShell any further.
I would prefer #159.

**Comment by kyrielia** [comment]
Also seeing this.

Latest version of chrome being picked up by `setup-chromedriver`: `115.0.5790.110`
However latest stable of chrome is: `115.0.5790.170`

Personally I would like to be able to have a parameter in this action where I pass which version of Chrome I would like to use, and this gets passed into the matrix lookup

**Comment by kyrielia** [comment]
I think that @petschki's comment in https://github.com/nanasess/setup-chromedriver/issues/199 is valid. I.e. allowing you specify that would like to use Chrome's latest `stable` build.

This is a feature in https://github.com/browser-actions/setup-chrome, for example.

**Comment by mingyaulee** [comment]
I am currently having this problem but running in windows-latest. Can the [fix commit](https://github.com/nanasess/setup-chromedriver/commit/835fd4bbfbcbd1cf8500e1f5918c838c9b96acb3) be adopted in the ps1 to ensure cross platform consistency?
