### ISSUE TITLE
Does Not Work On Windows

### ISSUE THREAD

**Issue by rmorshea** [nanasess/setup-chromedriver#24]
```
Run nanasess/setup-chromedriver@master
##setup chromedriver
Error: Unable to locate executable file: D:\a\_actions\nanasess\setup-chromedriver\master\lib\setup-chromedriver.sh. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
```

**Comment by rmorshea** [comment]
Looks like tests for this are now running on `windows-latest`: https://github.com/nanasess/setup-chromedriver/blob/1e49675a423700d7cd742cd118f3d3ab530a38a5/.github/workflows/test.yml#L24

**Comment by rmorshea** [comment]
I think this doesn't work because `.sh` file extensions are not executable under Windows.

**Comment by nanasess** [comment]
@rmorshea Welcome to setup-chromedriver, thanks for the detailed issue.
Windows was not supported, but we are trying to support it now.
Please wait for a while.

**Comment by rmorshea** [comment]
This is my solution at present: https://github.com/idom-team/idom/blob/5694ce620fdf66a8b852373e949161a12d06472e/.github/workflows/test.yml#L55

**Comment by nanasess** [comment]
@rmorshea 
Thanks you so much!, Fixed version has been released.
https://github.com/nanasess/setup-chromedriver/releases/tag/v1.0.5
