### ISSUE TITLE
Usage of Node.js 16 causes deprecated warnings and requires upgrade to Node.js 20

### ISSUE THREAD

**Issue by steve-todorov** [nanasess/setup-chromedriver#273]
## Details

Github has decided to transition from Node.js 16 to Node.js 20. Because of this we're getting some deprecation notices such as this one:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: `nanasess/setup-chromedriver@v2`. 
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

## Tasklist 

- [ ] Check the Github article
- [ ] Assert what needs to be done in order to upgrade (if necessary make a list)
- [ ] Upgrade to Node.js 20

**Comment by rcarroll901** [comment]
My builds started failing today with the above warning and 

```The process '/home/runner/work/_actions/nanasess/setup-chromedriver/master/lib/setup-chromedriver.sh' failed with exit code 2```

It built fine the first time today. After subsequent builds failed, I reran the build that had just been successful, and it failed too.

**Comment by steve-todorov** [comment]
@nanasess it looks to me like the only thing we need to change is this particular line:

https://github.com/nanasess/setup-chromedriver/blob/c67820cac58d458621d79b77cfa5c87e1d20dbb9/action.yml#L8-L10

The `package.json` file seems to be already using `@types/node`. Is there anything else that's needed to be done?
Would you have time to make a release soon?

**Comment by nanasess** [comment]
@steve-todorov 
Thanks for the detailed issue, It will be released today, Japan time.
Please wait a little longer.

**Comment by steve-todorov** [comment]
Sweet! Many thanks for the fast response and reaction!
