### ISSUE TITLE
why dose this error appear?

### ISSUE THREAD

**Issue by chloe5685** [nanasess/setup-chromedriver#313]
![{715CFA81-7660-481D-BEAC-D14B4A557BED}](https://github.com/nanasess/setup-chromedriver/assets/68677246/8b076eee-a42b-4cca-a14d-31e397beab9b)
How can I fix it?
Thank you in advance

**Comment by nanasess** [comment]
@chloe5685 It appears to be an error that occurs when the google-chrome version and chromedriver version do not match.

**Comment by chloe5685** [comment]
![image](https://github.com/nanasess/setup-chromedriver/assets/68677246/73b4fed1-e537-4767-bb68-cc9e5693fc70)
Yeah, it said the version of chrome and chromedriver didn't match at first, so I changed the version of chromedriver to the one recommeded, and the notice was gone but the error was still there

**Comment by nanasess** [comment]
@chloe5685 
What version of Google Chrome do you have?
If you do not specify a chromedriver version, it will automatically download the same version of chromedriver as Google Chrome.

**Comment by chloe5685** [comment]
> @chloe5685 What version of Google Chrome do you have? If you do not specify a chromedriver version, it will automatically download the same version of chromedriver as Google Chrome.

First time, it's 88 in defalt. The second time, I changed it to 125 as recommended, it did't work. After I read your reply, I didn't specify the version and tried again. And still, it didn't work.

**Comment by chloe5685** [comment]
> @chloe5685 What version of Google Chrome do you have? If you do not specify a chromedriver version, it will automatically download the same version of chromedriver as Google Chrome.

I found the solution. The error is not resulted by the versions. It's the sandbox mode of the chrome, so I disabled it.
